name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Copy .env
        run: cp .env.example .env

      - name: Cache Composer
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

      - name: Build Base Image
        run: docker build -f docker/base/Dockerfile.base -t laravel-infra-base:latest .

      - name: Build Prod Image
        run: |
          TAG=test
          docker build -f docker/prod/Dockerfile.prod -t laravel-app:"$TAG" .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'laravel-app:test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          report-format: sarif
          report-path: gitleaks.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: gitleaks.sarif

